In [450]:
import pandas as pd
from numpy import *


In [451]:
dataset= pd.read_csv(r"C:\Users\Tassos/Maria-Nearest neighbours/spots.csv")
dataset

C:\Users\Tassos\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning:

Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37) have mixed types.Specify dtype option on import or set low_memory=False.



LABEL       ID  TRACK_ID    QUALITY          POSITION_X  \
0         Label  Spot ID  Track ID    Quality                   X   
1         Label  Spot ID  Track ID    Quality                   X   
2           NaN      NaN       NaN  (quality)             (pixel)   
3      ID106497   106497         0     2051.0  467.97972424979724   
4       ID74243    74243         0     2885.0  425.56013775539736   
...         ...      ...       ...        ...                 ...   
54154  ID117187   117187      1138        903             681.996   
54155  ID117181   117181      1139        878               546.3   
54156  ID117273   117273      1139        973             547.931   
54157  ID117509   117509      1140       1550              1001.5   
54158  ID117480   117480      1140       1504             1002.29   

              POSITION_Y POSITION_Z POSITION_T  FRAME              RADIUS  \
0                      Y          Z          T  Frame              Radius   
1                      Y          Z          T  Frame                   R   
2                (pixel)    (pixel)      (sec)    NaN             (pixel)   
3       564.266504460665        0.0      160.0    160   25.57590303601595   
4      538.2393644729988        0.0       55.0     55  30.274961887114333   
...                  ...        ...        ...    ...                 ...   
54154            197.815          0        192    192              16.921   
54155            186.885          0        192    192             16.6268   
54156             190.45          0        193    193             17.5987   
54157            432.267          0        193    193             22.2444   
54158            432.961          0        192    192             21.8692   

       ...           ELLIPSE_X0              ELLIPSE_Y0       ELLIPSE_MAJOR  \
0      ...    Ellipse center x0       Ellipse center y0   Ellipse long axis   
1      ...               El. x0                  El. y0       El. long axis   
2      ...              (pixel)                 (pixel)             (pixel)   
3      ...   0.1955013270826286  -0.0073089549876495605  28.693832942766313   
4      ...  0.15300412766912866    -0.17142267294030122  37.266309411774934   
...    ...                  ...                     ...                 ...   
54154  ...             0.425094                 1.45024             21.3092   
54155  ...            -0.167158                0.591904             23.8691   
54156  ...            0.0804791               -0.286602             25.7624   
54157  ...             0.392439                0.249797             26.1083   
54158  ...              2.07494                0.331926             26.1181   

            ELLIPSE_MINOR         ELLIPSE_THETA   ELLIPSE_ASPECTRATIO  \
0      Ellipse short axis         Ellipse angle  Ellipse aspect ratio   
1            El. sh. axis             El. angle              El. a.r.   
2                 (pixel)             (radians)                   NaN   
3      23.829925199331683    0.6648863756551361    1.2041092325195817   
4      25.202050457476773  -0.01596289306428906    1.4787014840182982   
...                   ...                   ...                   ...   
54154             15.9544               1.41617               1.33563   
54155             12.4334              0.679046               1.91976   
54156             13.1156               0.47789               1.96425   
54157             20.4583              0.931572               1.27617   
54158             21.6265              0.473979               1.20769   

                     AREA           PERIMETER         CIRCULARITY  \
0                    Area           Perimeter         Circularity   
1                    Area              Perim.               Circ.   
2               (pixel^2)             (pixel)                 NaN   
3      2055.0000000000005  175.14970912281836  0.8417882306447596   
4       2879.500000000001  220.00254460531062  0.7476038665749605   
...             

In [452]:
dt=dataset.drop([0,1,2])
#print(dt)

In [453]:
mat=zeros((1024,1024,3))
mat
dtsp = dt[["ID","POSITION_X","POSITION_Y","FRAME","RADIUS","ELLIPSE_MAJOR","ELLIPSE_MINOR","ELLIPSE_THETA"]]
dtsp=dtsp.loc[dtsp['FRAME'] == 1]
dtsp

ID POSITION_X POSITION_Y FRAME   RADIUS ELLIPSE_MAJOR ELLIPSE_MINOR  \
16469  61149    638.711    560.456     1  26.9131       30.5799       24.5575   
16594  60639    560.717    165.557     1  27.8889       35.2894       23.2329   
16787  61152    874.481    555.009     1  22.2908       25.9462       20.5656   
16909  60643    296.236    171.035     1  28.2546       33.4295       24.5595   
17027  61160    761.446    561.499     1  24.2897       28.4546        22.239   
...      ...        ...        ...   ...      ...           ...           ...   
33028  60892    656.955     387.05     1  23.8065       28.1975       21.0546   
33239  60897    229.759     393.95     1  31.8805       38.0244       28.9954   
33537  60900    884.671    399.166     1  30.7134       34.0607       28.8633   
33587  60465    532.326    7.06483     1  15.5639       26.7747        10.295   
33599  60494    605.558    39.0853     1  18.5669       21.4408       17.7951   

      ELLIPSE_THETA  
16469       1.54522  
16594      0.392112  
16787       2.36856  
16909       2.49592  
17027       2.35997  
...             ...  
33028       2.50238  
33239     0.0376586  
33537       1.46329  
33587     -0.046666  
33599     -0.229552  

[108 rows x 8 columns]

In [454]:
dtsp=dtsp.reset_index()
dtsp=dtsp.drop(columns=['index'])
dtsp

ID POSITION_X POSITION_Y FRAME   RADIUS ELLIPSE_MAJOR ELLIPSE_MINOR  \
0    61149    638.711    560.456     1  26.9131       30.5799       24.5575   
1    60639    560.717    165.557     1  27.8889       35.2894       23.2329   
2    61152    874.481    555.009     1  22.2908       25.9462       20.5656   
3    60643    296.236    171.035     1  28.2546       33.4295       24.5595   
4    61160    761.446    561.499     1  24.2897       28.4546        22.239   
..     ...        ...        ...   ...      ...           ...           ...   
103  60892    656.955     387.05     1  23.8065       28.1975       21.0546   
104  60897    229.759     393.95     1  31.8805       38.0244       28.9954   
105  60900    884.671    399.166     1  30.7134       34.0607       28.8633   
106  60465    532.326    7.06483     1  15.5639       26.7747        10.295   
107  60494    605.558    39.0853     1  18.5669       21.4408       17.7951   

    ELLIPSE_THETA  
0         1.54522  
1        0.392112  
2         2.36856  
3         2.49592  
4         2.35997  
..            ...  
103       2.50238  
104     0.0376586  
105       1.46329  
106     -0.046666  
107     -0.229552  

[108 rows x 8 columns]

In [455]:
X,Y=array(dtsp[["POSITION_X"]].astype(int)),array(dtsp[["POSITION_Y"]].astype(int))
ID=array(dtsp[["ID"]])
rad=array(dtsp[["ELLIPSE_MAJOR"]])
X=X.reshape(-1)
Y=Y.reshape(-1)


In [456]:
for i in range(108):
    
    mat[X[i],Y[i],0]=1
    mat[X[i],Y[i],1]=ID[i]
    mat[X[i],Y[i],2]=rad[i]
    
#print(mat)

In [457]:
ID_num_neigh=zeros((len(X),2))
ID_num_neigh[:,1]=-1
ID_num_neigh[:,0]=ID.reshape(-1)
ID_num_neigh



array([[ 6.1149e+04, -1.0000e+00],
       [ 6.0639e+04, -1.0000e+00],
       [ 6.1152e+04, -1.0000e+00],
       [ 6.0643e+04, -1.0000e+00],
       [ 6.1160e+04, -1.0000e+00],
       [ 6.1164e+04, -1.0000e+00],
       [ 6.0656e+04, -1.0000e+00],
       [ 6.1168e+04, -1.0000e+00],
       [ 6.0659e+04, -1.0000e+00],
       [ 6.1171e+04, -1.0000e+00],
       [ 6.0663e+04, -1.0000e+00],
       [ 6.1175e+04, -1.0000e+00],
       [ 6.1177e+04, -1.0000e+00],
       [ 6.0667e+04, -1.0000e+00],
       [ 6.1180e+04, -1.0000e+00],
       [ 6.0669e+04, -1.0000e+00],
       [ 6.1183e+04, -1.0000e+00],
       [ 6.0674e+04, -1.0000e+00],
       [ 6.1186e+04, -1.0000e+00],
       [ 6.1188e+04, -1.0000e+00],
       [ 6.0679e+04, -1.0000e+00],
       [ 6.0681e+04, -1.0000e+00],
       [ 6.0685e+04, -1.0000e+00],
       [ 6.0688e+04, -1.0000e+00],
       [ 6.0689e+04, -1.0000e+00],
       [ 6.0693e+04, -1.0000e+00],
       [ 6.0697e+04, -1.0000e+00],
       [ 6.0699e+04, -1.0000e+00],
       [ 6.0702e+04,

In [433]:
for _ in range(len(ID_num_neigh)):
    for i in range(X[_]-200,X[_]+200):
        for j in range(Y[_]-200,Y[_]+200):
            if i<1024 and j< 1024:
                
                if mat[i,j,0]==1:
                    r=((i-X[_])**2+(j-Y[_])**2)**(0.5)
                    if r<=abs(mat[i,j,2]+mat[X[_],Y[_],2]):
                        ID_num_neigh[_,1]=ID_num_neigh[_,1]+1
                       

                    

In [458]:
import sys
set_printoptions(threshold=sys.maxsize)
            
print(ID_num_neigh.astype(int))

[[61149    -1]
 [60639    -1]
 [61152    -1]
 [60643    -1]
 [61160    -1]
 [61164    -1]
 [60656    -1]
 [61168    -1]
 [60659    -1]
 [61171    -1]
 [60663    -1]
 [61175    -1]
 [61177    -1]
 [60667    -1]
 [61180    -1]
 [60669    -1]
 [61183    -1]
 [60674    -1]
 [61186    -1]
 [61188    -1]
 [60679    -1]
 [60681    -1]
 [60685    -1]
 [60688    -1]
 [60689    -1]
 [60693    -1]
 [60697    -1]
 [60699    -1]
 [60702    -1]
 [60705    -1]
 [60706    -1]
 [60712    -1]
 [60715    -1]
 [61232    -1]
 [60723    -1]
 [61235    -1]
 [60726    -1]
 [60732    -1]
 [61244    -1]
 [61247    -1]
 [60736    -1]
 [60741    -1]
 [61256    -1]
 [60746    -1]
 [61260    -1]
 [60749    -1]
 [60752    -1]
 [61264    -1]
 [61267    -1]
 [60756    -1]
 [61271    -1]
 [60760    -1]
 [61275    -1]
 [60765    -1]
 [61279    -1]
 [60769    -1]
 [60772    -1]
 [61284    -1]
 [61288    -1]
 [60778    -1]
 [61291    -1]
 [60782    -1]
 [60787    -1]
 [61301    -1]
 [60790    -1]
 [60794    -1]
 [60797   

In [496]:
import numpy as np
#matrix=zeros((1024,1024))
def elipsoid (major,minor,thet,x0,y0):
    dummymat=(zeros((1024,1024)))
    matrix=zeros((1024,1024))
    for i in range(int(x0-major-1),int(x0+major+1)):
        for j in range(int(y0-major-1),int(y0+major+1)):
            if i<1024-major and i>0 and j<1024-major and j>0:
                if (i-x0)**2/(major+5)**2+(j-y0)**2/(minor+5)**2<=1:
                    dummymat[i,j]=1
                    if i<1024 and i>0 and j<1024 and j>0:
                        a=np.cos(thet/3.14*180.)*abs(i-x0)+y0
                        b=np.sin(thet/3.14*180.)*abs(j-y0)+x0
                        if a>0 and b>0 and a<1024 and b<1024:
                            matrix[int(b),int(a)]=dummymat[i,j]
                            matrix=array(matrix)
    return matrix


In [497]:
X,Y=array(dtsp[["POSITION_X"]].astype(int)).reshape(-1),array(dtsp[["POSITION_Y"]].astype(int)).reshape(-1)
ID=array(dtsp[["ID"]])
major=array(dtsp[["ELLIPSE_MAJOR"]]).reshape(-1)
minor=array(dtsp[["ELLIPSE_MINOR"]]).reshape(-1)
theta=array(dtsp[["ELLIPSE_THETA"]]).reshape(-1)



In [498]:
e1=zeros((1024,1024))
e2=zeros((1024,1024))
for _ in range(len(ID_num_neigh)):
   # matrix1=zeros((1024,1024))
    
    e1=elipsoid(major[_],minor[_],theta[_],X[_],Y[_])
    #for i in range(int(X[_])-100,int(X[_])+100):
        #for j in range(int(Y[_])-100,int(Y[_])+200):
            #if i<1024 and j< 1024:
                
                #if mat[i,j,0]==1:
    for __ in range(len(ID_num_neigh)):
                            
                            #if mat[i,j,2]==ID_num_neigh[__,0]:
                                #matrix2=zeros((1024,1024))
                                e2=elipsoid(major[__],minor[__],theta[__],X[__],Y[__])
                                e=array(e1)+array(e2)
                        
                                if amax(e)==2:
                                    ID_num_neigh[_,1]=ID_num_neigh[_,1]+1
                                    
print(ID_num_neigh.astype(int))                

[[61149     7]
 [60639     0]
 [61152     0]
 [60643     0]
 [61160     0]
 [61164     0]
 [60656     0]
 [61168     0]
 [60659     0]
 [61171     1]
 [60663     0]
 [61175     0]
 [61177     0]
 [60667     0]
 [61180     0]
 [60669     0]
 [61183     0]
 [60674     0]
 [61186     0]
 [61188     0]
 [60679     0]
 [60681     0]
 [60685     0]
 [60688     0]
 [60689     0]
 [60693     0]
 [60697     1]
 [60699     0]
 [60702     0]
 [60705     0]
 [60706     0]
 [60712     0]
 [60715     0]
 [61232     0]
 [60723     0]
 [61235     0]
 [60726     0]
 [60732     0]
 [61244     0]
 [61247     0]
 [60736     0]
 [60741     0]
 [61256     1]
 [60746     0]
 [61260     1]
 [60749     0]
 [60752     1]
 [61264     1]
 [61267     0]
 [60756     0]
 [61271     0]
 [60760     0]
 [61275     0]
 [60765     0]
 [61279     0]
 [60769     0]
 [60772     0]
 [61284     0]
 [61288     0]
 [60778     0]
 [61291     0]
 [60782     0]
 [60787     0]
 [61301     0]
 [60790     0]
 [60794     0]
 [60797   